const Hackathon = require('../models/Hackathon');

const sampleHackathons = [
  {
    title: 'Global Startup Hack 2026',
    description: 'Build a complete MVP in 48 hours with mentorship from startup founders, product designers, and experienced engineers. Perfect for teams looking to validate their startup ideas.',
    domain: 'Startup',
    tags: ['MVP', 'Product Design', 'Startup Strategy', 'Pitching'],
    teamSize: '3-5',
    experienceLevel: 'Intermediate',
    isOnline: true,
    beginnerFriendly: false,
    location: 'Online',
    startDate: new Date('2026-07-01T10:00:00Z'),
    endDate: new Date('2026-07-03T18:00:00Z'),
    url: ' https://unstop.com/hackathons?oppstatus=open&usertype=students&domain=2&course=8&specialization=Computer%20Science%20and%20Engineering&passingOutYear=2030',
  },
  {
    title: 'AI for Good Hackathon',
    description: 'Create innovative AI solutions that address real-world sustainability challenges and social impact. Great for beginners interested in machine learning and AI applications.',
    domain: 'AI/ML',
    tags: ['AI', 'Machine Learning', 'Sustainability', 'Social Impact'],
    teamSize: '2-4',
    experienceLevel: 'Beginner',
    isOnline: true,
    beginnerFriendly: true,
    location: 'Online',
    startDate: new Date('2026-08-10T12:00:00Z'),
    endDate: new Date('2026-08-12T20:00:00Z'),
    url: 'https://example.com/ai-for-good',
  },
  {
    title: 'Campus Innovators Challenge',
    description: 'College-focused hackathon with hands-on mentorship in product development, design thinking, and various tech stacks. Network with fellow student innovators.',
    domain: 'Web Development',
    tags: ['College', 'Networking', 'Product Development', 'Tech Stacks'],
    teamSize: '2-6',
    experienceLevel: 'Beginner',
    isOnline: false,
    beginnerFriendly: true,
    location: 'San Francisco, CA',
    startDate: new Date('2026-09-15T09:00:00Z'),
    endDate: new Date('2026-09-17T17:00:00Z'),
    url: 'https://example.com/campus-innovators',
  },
  {
    title: 'Mobile App Development Sprint',
    description: 'Fast-paced hackathon focused on building native and cross-platform mobile applications. Learn from expert mobile engineers and submit your app to app stores.',
    domain: 'Mobile Development',
    tags: ['iOS', 'Android', 'React Native', 'App Design'],
    teamSize: '2-5',
    experienceLevel: 'Intermediate',
    isOnline: true,
    beginnerFriendly: false,
    location: 'Online',
    startDate: new Date('2026-10-05T14:00:00Z'),
    endDate: new Date('2026-10-07T22:00:00Z'),
    url: 'https://example.com/mobile-sprint',
  },
  {
    title: 'Beginner Web Dev Workshop Hackathon',
    description: 'Perfect for absolute beginners! Learn HTML, CSS, JavaScript, and React while building a complete web application. No prior experience needed.',
    domain: 'Web Development',
    tags: ['HTML', 'CSS', 'JavaScript', 'React', 'Beginner-Friendly'],
    teamSize: '1-3',
    experienceLevel: 'Beginner',
    isOnline: true,
    beginnerFriendly: true,
    location: 'Online',
    startDate: new Date('2026-06-20T10:00:00Z'),
    endDate: new Date('2026-06-22T18:00:00Z'),
    url: 'https://example.com/beginner-webdev',
  },
  {
    title: 'Blockchain & Web3 Hack',
    description: 'Build decentralized applications, smart contracts, and explore the world of Web3. Suitable for experienced developers interested in blockchain technology.',
    domain: 'Blockchain',
    tags: ['Solidity', 'Smart Contracts', 'DeFi', 'NFTs', 'Web3'],
    teamSize: '3-5',
    experienceLevel: 'Advanced',
    isOnline: true,
    beginnerFriendly: false,
    location: 'Online',
    startDate: new Date('2026-11-01T13:00:00Z'),
    endDate: new Date('2026-11-03T21:00:00Z'),
    url: 'https://example.com/blockchain-hack',
  },
  {
    title: 'Data Science & Analytics Summit',
    description: 'Work with real datasets and build predictive models, dashboards, and data visualizations. Collaborate with data scientists and business analysts.',
    domain: 'Data Science',
    tags: ['Python', 'Data Analysis', 'Machine Learning', 'Visualization'],
    teamSize: '2-4',
    experienceLevel: 'Intermediate',
    isOnline: false,
    beginnerFriendly: false,
    location: 'New York, NY',
    startDate: new Date('2026-10-20T09:00:00Z'),
    endDate: new Date('2026-10-22T17:00:00Z'),
    url: 'https://example.com/data-science-summit',
  },
  {
    title: 'Game Development Jam',
    description: 'Create a fun game in 48 hours using modern game engines. No previous game development experience required. Great community and awesome prizes!',
    domain: 'Game Development',
    tags: ['Unity', 'Unreal', 'Game Design', 'Graphics'],
    teamSize: '2-5',
    experienceLevel: 'Beginner',
    isOnline: true,
    beginnerFriendly: true,
    location: 'Online',
    startDate: new Date('2026-07-15T12:00:00Z'),
    endDate: new Date('2026-07-17T20:00:00Z'),
    url: 'https://example.com/game-jam',
  },
  {
    title: 'Cloud Infrastructure & DevOps Challenge',
    description: 'Deploy scalable applications on cloud platforms. Learn Docker, Kubernetes, AWS, and modern DevOps practices from industry experts.',
    domain: 'Cloud/DevOps',
    tags: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Infrastructure'],
    teamSize: '2-4',
    experienceLevel: 'Advanced',
    isOnline: true,
    beginnerFriendly: false,
    location: 'Online',
    startDate: new Date('2026-09-01T10:00:00Z'),
    endDate: new Date('2026-09-03T18:00:00Z'),
    url: 'https://example.com/devops-challenge',
  },
  {
    title: 'IoT & Hardware Innovations',
    description: 'Build intelligent IoT solutions and hardware projects. Work with Arduino, Raspberry Pi, and IoT platforms. Beginner-friendly with provided hardware kits.',
    domain: 'IoT/Hardware',
    tags: ['Arduino', 'Raspberry Pi', 'IoT', 'Sensors', 'Embedded Systems'],
    teamSize: '2-4',
    experienceLevel: 'Beginner',
    isOnline: false,
    beginnerFriendly: true,
    location: 'Seattle, WA',
    startDate: new Date('2026-08-25T09:00:00Z'),
    endDate: new Date('2026-08-27T17:00:00Z'),
    url: 'https://example.com/iot-innovations',
  },
];

async function seedHackathons() {
  try {
    const count = await Hackathon.countDocuments();
    if (count === 0) {
      await Hackathon.insertMany(sampleHackathons);
      console.log('✓ Seeded 10 sample hackathons');
    } else {
      console.log(`✓ Database already contains ${count} hackathons. Skipping seed.`);
    }
  } catch (error) {
    console.error('Error seeding hackathons:', error.message);
  }
}

module.exports = { seedHackathons };
